version: "2"

services:
  proxy:
    image: nginx:1.17.2-alpine-perl
    # depends_on:
    #   - node
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html
    ports:
     - "8099:8099"
    # command: /bin/bash -c "nginx -g 'daemon off;'"
